#!/bin/bash
# set -e

echo "Installing dependencies..."
echo "SMHP TRAINING OP NPROC_PER_NODE: ${NPROC_PER_NODE}"
echo "SMHP TRAINING OP NNODES: ${NNODES}"

LOCAL_WORKDIR=/docker_workspace

cd $LOCAL_WORKDIR

SCRIPT_RECIPE_PROJECT_PATH=${SCRIPT_RECIPE_PROJECT_PATH%/*}
cp -r $SCRIPT_RECIPE_PROJECT_PATH/* ./


exec sh $SCRIPT_RECIPE_ENTRY_PATH

