---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: olm-MODEL_TAG-inference
  labels:
    app: olm-MODEL_TAG-inference
    model-type: "ollama"
    deployment-tag: "MODEL_TAG"
spec:
  replicas: REPLICAS_COUNT
  selector:
    matchLabels:
      app: olm-MODEL_TAG-inference
  template:
    metadata:
      labels:
        app: olm-MODEL_TAG-inference
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:latest
          resources:
            limits:
              nvidia.com/gpu: GPU_COUNT
            requests:
              cpu: "8"
              memory: 16Gi
              nvidia.com/gpu: GPU_COUNT
          env:
            - name: OLLAMA_HOST
              value: "0.0.0.0"
            - name: OLLAMA_ORIGINS
              value: "*"
          ports:
            - containerPort: 11434
              name: http
          volumeMounts:
            - name: ollama-cache
              mountPath: /root/.ollama
            - name: shm
              mountPath: /dev/shm
          # 启动后自动拉取模型
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - |
                    sleep 10
                    ollama pull OLLAMA_MODEL_ID || true
          livenessProbe:
            httpGet:
              path: /
              port: 11434
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 11434
            initialDelaySeconds: 30
            periodSeconds: 10
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
      volumes:
        - name: ollama-cache
          hostPath:
            path: /opt/dlami/nvme/.ollama
            type: DirectoryOrCreate
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 2Gi
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - olm-MODEL_TAG-inference
              topologyKey: kubernetes.io/hostname
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: olm-MODEL_TAG-nlb
  annotations: NLB_ANNOTATIONS
spec:
  ports:
    - port: 11434
      protocol: TCP
      targetPort: http
  selector:
    app: olm-MODEL_TAG-inference
  type: LoadBalancer
