apiVersion: sagemaker.services.k8s.aws/v1alpha1
kind: TrainingJob
metadata:
  name: TRAINING_JOB_NAME
  namespace: default
spec:
  trainingJobName: TRAINING_JOB_NAME
  roleARN: "SAGEMAKER_DEV_ROLE"
  
  algorithmSpecification:
    trainingImage: DOCKER_IMAGE
    trainingInputMode: FastFile
  
  inputDataConfig:
  - channelName: userdatas
    dataSource:
      s3DataSource:
        s3DataType: S3Prefix
        s3URI: s3://FUSE_S3_PATH/SM_JOB/SAGEMAKER_JOB_DIR/
        s3DataDistributionType: FullyReplicated
    compressionType: None
  
  outputDataConfig:
    s3OutputPath: s3://FUSE_S3_PATH/SM_JOB/SAGEMAKER_JOB_DIR/output/
  
  resourceConfig:
    instanceType: INSTANCE_TYPE
    instanceCount: REPLICAS_COUNT
    volumeSizeInGB: 200
    keepAlivePeriodInSeconds: 1200
  
  stoppingCondition:
    maxRuntimeInSeconds: 86400
    # maxWaitTimeInSeconds: SPOT_MAX_WAIT_TIME
  
  enableManagedSpotTraining: SPOT_TRAINING_ENABLED
  
  checkpointConfig:
    s3URI: s3://FUSE_S3_PATH/SM_JOB/SAGEMAKER_JOB_DIR/checkpoints/
    localPath: /opt/ml/checkpoints
  
  # hyperParameters:
  #   batch-size: "64"
  #   epochs: "10"
  #   lr: "0.005"
  
  environment:
    SAGEMAKER_PROGRAM: "/opt/ml/input/data/userdatas/ENTRY_PYTHON_PATH"
    SM_PATH: "/opt/ml/input/data/userdatas"
    # NCCL_SOCKET_IFNAME: "eth0"
    FI_PROVIDER: "efa"
    NCCL_DEBUG: "DEBUG"
    NPROC_PER_NODE: GPU_PER_NODE
    N_NODES: NUM_REPLICAS
    BASE_JOB_NAME: TRAINING_JOB_NAME
    HYP_PARAMS: "PYTHON_SCRIPT_PARAMS"
